"use strict";

function createRuntimeHelpers({
  vscode,
  fs,
  fsp,
  path,
  os,
  output,
  loginReadyRe,
  resolveCodexBin,
  codexHomeSetting,
  codexHomePlan,
  sandboxModeSetting,
  positiveNumberSetting,
  extensionSetting,
  watchdogRoleSetting,
  booleanSetting,
  servicePrefixSetting,
  defaultTimeoutMinutes,
  defaultIntervalMinutes,
  defaultCompactEveryRuns,
  defaultPhaseOffsetMinutes,
  defaultSupervisorLightFollowup,
  defaultSupervisorAuditEveryRunnerRuns,
  updateProjectSetting,
  watcherProfileModelDefaults,
  mergeWatcherConfigText,
  hasTomlAssignment,
  parseTomlBasicString,
  run,
  ensureDir,
  unitNames,
  systemdQuote,
  systemdPathValue,
  systemdEnvValue,
  shellQuote,
  getProjectRoot,
  readFilePrefix
}) {
  async function effectiveWatchdogSettings(root) {
    return {
      codexBin: await resolveCodexBin(root),
      codexHome: codexHomeSetting(root),
      sandboxMode: sandboxModeSetting(root),
      intervalMinutes: positiveNumberSetting(root, "codexWatchdog.intervalMinutes", extensionSetting("intervalMinutes", defaultIntervalMinutes), 5, defaultIntervalMinutes),
      timeoutMinutes: positiveNumberSetting(root, "codexWatchdog.timeoutMinutes", extensionSetting("timeoutMinutes", defaultTimeoutMinutes), 1, defaultTimeoutMinutes),
      compactEveryRuns: positiveNumberSetting(root, "codexWatchdog.compactEveryRuns", extensionSetting("compactEveryRuns", defaultCompactEveryRuns), 0, defaultCompactEveryRuns),
      role: watchdogRoleSetting(root),
      phaseOffsetMinutes: positiveNumberSetting(root, "codexWatchdog.phaseOffsetMinutes", extensionSetting("phaseOffsetMinutes", defaultPhaseOffsetMinutes), 0, defaultPhaseOffsetMinutes),
      supervisorLightFollowup: booleanSetting(root, "codexWatchdog.supervisorLightFollowup", extensionSetting("supervisorLightFollowup", defaultSupervisorLightFollowup), defaultSupervisorLightFollowup),
      supervisorAuditEveryRunnerRuns: positiveNumberSetting(root, "codexWatchdog.supervisorAuditEveryRunnerRuns", extensionSetting("supervisorAuditEveryRunnerRuns", defaultSupervisorAuditEveryRunnerRuns), 1, defaultSupervisorAuditEveryRunnerRuns),
      servicePrefix: servicePrefixSetting(root)
    };
  }

  async function renderWatchdogEnv(root) {
    const settings = await effectiveWatchdogSettings(root);
    return [
      "# Generated by Codex Watchdog. No secrets are stored here.",
      "# This file keeps VSCode control-panel startup and project-local CLI startup aligned.",
      `CODEX_BIN=${shellQuote(settings.codexBin)}`,
      `CODEX_HOME=${shellQuote(settings.codexHome)}`,
      `CODEX_SANDBOX_MODE=${shellQuote(settings.sandboxMode)}`,
      `WATCHDOG_INTERVAL_MINUTES=${shellQuote(String(settings.intervalMinutes))}`,
      `WATCHDOG_TIMEOUT_MINUTES=${shellQuote(String(settings.timeoutMinutes))}`,
      `WATCHDOG_COMPACT_EVERY_RUNS=${shellQuote(String(settings.compactEveryRuns))}`,
      `WATCHDOG_ROLE=${shellQuote(settings.role)}`,
      `WATCHDOG_PHASE_OFFSET_MINUTES=${shellQuote(String(settings.phaseOffsetMinutes))}`,
      `WATCHDOG_SUPERVISOR_LIGHT_FOLLOWUP=${shellQuote(settings.supervisorLightFollowup ? "1" : "0")}`,
      `WATCHDOG_SUPERVISOR_AUDIT_EVERY_RUNNER_RUNS=${shellQuote(String(settings.supervisorAuditEveryRunnerRuns))}`,
      `WATCHDOG_SERVICE_PREFIX=${shellQuote(settings.servicePrefix)}`,
      ""
    ].join("\n");
  }

  async function writeSystemdUnits(root, units) {
    const unitDir = path.join(os.homedir(), ".config", "systemd", "user");
    await ensureDir(unitDir);

    const settings = await effectiveWatchdogSettings(root);
    const interval = settings.intervalMinutes;
    const timeout = settings.timeoutMinutes;
    const codexBin = settings.codexBin;
    const codexHome = settings.codexHome;
    const sandboxMode = settings.sandboxMode;
    const compactEveryRuns = settings.compactEveryRuns;
    const role = settings.role;
    const phaseOffsetMinutes = settings.phaseOffsetMinutes;
    const supervisorLightFollowup = settings.supervisorLightFollowup ? "1" : "0";
    const supervisorAuditEveryRunnerRuns = settings.supervisorAuditEveryRunnerRuns;

    const service = [
      "[Unit]",
      `Description=Codex project watcher for ${path.basename(root)}`,
      "",
      "[Service]",
      "Type=oneshot",
      `WorkingDirectory=${systemdPathValue(root)}`,
      `ExecStart=${systemdQuote("/usr/bin/env")} bash ${systemdQuote(path.join(root, "agent", "bin", "run_watchdog.sh"))}`,
      `Environment=CODEX_BIN=${systemdEnvValue(codexBin)}`,
      `Environment=CODEX_HOME=${systemdEnvValue(codexHome)}`,
      `Environment=CODEX_SANDBOX_MODE=${systemdEnvValue(sandboxMode)}`,
      `Environment=WATCHDOG_TIMEOUT_MINUTES=${timeout}`,
      `Environment=WATCHDOG_COMPACT_EVERY_RUNS=${compactEveryRuns}`,
      `Environment=WATCHDOG_ROLE=${systemdEnvValue(role)}`,
      `Environment=WATCHDOG_PHASE_OFFSET_MINUTES=${phaseOffsetMinutes}`,
      `Environment=WATCHDOG_SUPERVISOR_LIGHT_FOLLOWUP=${supervisorLightFollowup}`,
      `Environment=WATCHDOG_SUPERVISOR_AUDIT_EVERY_RUNNER_RUNS=${supervisorAuditEveryRunnerRuns}`,
      "Environment=CUDA_VISIBLE_DEVICES=",
      "NoNewPrivileges=yes",
      "PrivateTmp=yes",
      "ProtectSystem=full",
      `TimeoutStartSec=${timeout}min`,
      ""
    ].join("\n");

    const timer = [
      "[Unit]",
      `Description=Run Codex project watcher every ${interval} minutes for ${path.basename(root)}`,
      "",
      "[Timer]",
      `OnActiveSec=${phaseOffsetMinutes}min`,
      `OnUnitActiveSec=${interval}min`,
      "AccuracySec=1min",
      `Unit=${units.service}`,
      "",
      "[Install]",
      "WantedBy=timers.target",
      ""
    ].join("\n");

    await fsp.writeFile(path.join(unitDir, units.service), service);
    await fsp.writeFile(path.join(unitDir, units.timer), timer);
    output.appendLine(`Wrote ${path.join(unitDir, units.service)}`);
    output.appendLine(`Wrote ${path.join(unitDir, units.timer)}`);
  }

  async function ensureCodexHome(root) {
    let plan = codexHomePlan(root);
    if (plan.requiresProjectSettingUpdate) {
      await updateProjectSetting(root, "codexWatchdog.codexHome", plan.effectivePath);
      output.appendLine(`[warning] ${plan.migrationReason}`);
      vscode.window.showInformationMessage(`Codex Watchdog moved this project's watcher home to ${plan.effectivePath}. Reinstall the timer after review so systemd uses the migrated CODEX_HOME.`);
      plan = codexHomePlan(root);
    }
    const codexHome = plan.effectivePath;
    await ensureDir(codexHome);
    const configPath = path.join(codexHome, "config.toml");
    const profileDefaults = watcherProfileModelDefaults();
    if (!fs.existsSync(configPath)) {
      const merged = mergeWatcherConfigText("", profileDefaults);
      await fsp.writeFile(configPath, merged.text);
      output.appendLine(`Wrote ${configPath}`);
      if (merged.inheritedModel) {
        output.appendLine("Seeded watcher model config from the main Codex profile.");
      }
    } else {
      const existing = await fsp.readFile(configPath, "utf8");
      const merged = mergeWatcherConfigText(existing, profileDefaults);
      if (merged.changed) {
        await fsp.writeFile(configPath, merged.text);
        output.appendLine(`Updated ${configPath}`);
        if (merged.inheritedModel && !hasTomlAssignment(existing, "model")) {
          output.appendLine("Seeded missing watcher model config from the main Codex profile.");
        }
      }
    }
  }

  function inspectWatcherHomeBootstrapState(watcherHome, mainCodexHome = path.join(os.homedir(), ".codex")) {
    const authPath = path.join(watcherHome, "auth.json");
    const configPath = path.join(watcherHome, "config.toml");
    const modelsCachePath = path.join(watcherHome, "models_cache.json");
    const mainAuthPath = path.join(mainCodexHome, "auth.json");
    const mainModelsCachePath = path.join(mainCodexHome, "models_cache.json");
    const configText = fs.existsSync(configPath) ? fs.readFileSync(configPath, "utf8") : "";
    const model = parseTomlBasicString(configText, "model");
    const modelReasoningEffort = parseTomlBasicString(configText, "model_reasoning_effort");
    const authExists = fs.existsSync(authPath);
    const mainAuthExists = fs.existsSync(mainAuthPath);
    const modelsCacheExists = fs.existsSync(modelsCachePath);
    const mainModelsCacheExists = fs.existsSync(mainModelsCachePath);
    const signals = [];

    if (!authExists) {
      signals.push("This watcher home does not have auth.json yet.");
      if (mainAuthExists) {
        signals.push("Your main ~/.codex profile is already logged in, so you can seed this watcher home locally or open a dedicated login terminal.");
      } else {
        signals.push("Open Login Terminal to create login state inside this CODEX_HOME.");
      }
    }
    if (!model) {
      signals.push("This watcher home does not declare a model in config.toml yet.");
    }
    if (authExists && !modelsCacheExists && mainModelsCacheExists) {
      signals.push("models_cache.json is still missing here; a local seed from ~/.codex can warm it up.");
    }

    return {
      watcherHome,
      authPath,
      configPath,
      modelsCachePath,
      model,
      modelReasoningEffort,
      authExists,
      configExists: fs.existsSync(configPath),
      modelsCacheExists,
      mainCodexHome,
      mainAuthPath,
      mainModelsCachePath,
      mainAuthExists,
      mainModelsCacheExists,
      canSeedFromMainAuth: mainAuthExists && (!authExists || !modelsCacheExists),
      bootstrapText: signals.join("\n")
    };
  }

  function inspectWatcherHomeBootstrap(root) {
    return inspectWatcherHomeBootstrapState(codexHomeSetting(root));
  }

  async function seedWatcherHomeBootstrapFromProfilePaths(watcherHome, mainCodexHome = path.join(os.homedir(), ".codex")) {
    await ensureDir(watcherHome);
    const copied = [];
    for (const fileName of ["auth.json", "models_cache.json"]) {
      const source = path.join(mainCodexHome, fileName);
      if (!fs.existsSync(source)) {
        continue;
      }
      const target = path.join(watcherHome, fileName);
      await fsp.copyFile(source, target);
      copied.push(fileName);
    }
    return {
      watcherHome,
      mainCodexHome,
      copied,
      copiedAuth: copied.includes("auth.json"),
      copiedModelsCache: copied.includes("models_cache.json")
    };
  }

  async function seedWatcherHomeAuthFromMainProfile(root) {
    return seedWatcherHomeBootstrapFromProfilePaths(codexHomeSetting(root));
  }

  async function getCodexLoginStatus(root) {
    try {
      const codexBin = await resolveCodexBin(root);
      const codexHome = codexHomeSetting(root);
      const bootstrap = inspectWatcherHomeBootstrapState(codexHome);
      const result = await run(codexBin, ["login", "status"], {
        cwd: root,
        env: { CODEX_HOME: codexHome },
        allowFailure: true,
        timeout: 10000
      });
      const combined = [result.stdout, result.stderr].filter(Boolean).join("\n").trim();
      const statusText = combined || (result.error ? result.error.message : "");
      const spawnMissing = result.error && (result.error.code === "ENOENT" || /ENOENT/.test(statusText));
      const ok = !result.error && loginReadyRe.test(statusText);

      if (ok) {
        return {
          ok: true,
          bootstrapText: bootstrap.bootstrapText,
          canSeedFromMainAuth: bootstrap.canSeedFromMainAuth,
          text: [
            statusText,
            "",
            `Watcher auth: ${bootstrap.authExists ? "present" : "missing"}`,
            `Watcher model: ${bootstrap.model || "not set"}`,
            bootstrap.modelReasoningEffort ? `Reasoning effort: ${bootstrap.modelReasoningEffort}` : "",
            `CODEX_HOME=${codexHome}`,
            `CODEX_BIN=${codexBin}`
          ].filter(Boolean).join("\n")
        };
      }

      return {
        ok: false,
        bootstrapText: bootstrap.bootstrapText,
        canSeedFromMainAuth: bootstrap.canSeedFromMainAuth,
        text: [
          spawnMissing
            ? "Codex CLI executable was not found for watchdog mode."
            : "Codex login is not ready for watchdog mode.",
          statusText || "No login status output was returned.",
          "",
          `Watcher auth: ${bootstrap.authExists ? "present" : "missing"}`,
          `Watcher model: ${bootstrap.model || "not set"}`,
          bootstrap.modelReasoningEffort ? `Reasoning effort: ${bootstrap.modelReasoningEffort}` : "",
          `CODEX_HOME=${codexHome}`,
          `CODEX_BIN=${codexBin}`
        ].filter(Boolean).join("\n")
      };
    } catch (error) {
      return {
        ok: false,
        text: `Could not check Codex login status: ${error.message || String(error)}`,
        bootstrapText: "",
        canSeedFromMainAuth: false
      };
    }
  }

  async function confirmLoginIfNeeded(root) {
    const login = await getCodexLoginStatus(root);
    if (login.ok) {
      return true;
    }

    const answer = await vscode.window.showWarningMessage(
      [
        login.text.includes("executable was not found")
          ? "Codex Watchdog could not find a Codex CLI executable."
          : "Codex Watchdog needs an OpenAI login before it can start unattended work.",
        "",
        ...(login.bootstrapText ? [login.bootstrapText, ""] : []),
        login.text,
        "",
        login.text.includes("executable was not found")
          ? "The project files and watchdog scripts are ready. Fix codexWatchdog.codexBin or install/enable the OpenAI Codex CLI, then run Start Guard again."
          : "The project files and watchdog scripts are ready. Complete login in the terminal, then run Start Guard again."
      ].join("\n"),
      { modal: true },
      ...(login.canSeedFromMainAuth ? ["Seed from Main Profile"] : []),
      "Open Login Terminal"
    );

    if (answer === "Seed from Main Profile") {
      const seeded = await seedWatcherHomeAuthFromMainProfile(root);
      if (!seeded.copiedAuth) {
        vscode.window.showWarningMessage("No ~/.codex/auth.json was found to seed this watcher home. Open Login Terminal instead.");
      } else {
        output.appendLine(`Seeded watcher auth bootstrap from ${seeded.mainCodexHome} into ${seeded.watcherHome}`);
        const recheck = await getCodexLoginStatus(root);
        if (recheck.ok) {
          vscode.window.showInformationMessage("Seeded watcher auth from the main Codex profile. Start Guard can continue now.");
          return true;
        }
        vscode.window.showWarningMessage("Seeded local watcher files, but this watcher home still needs a fresh login.");
      }
    }

    if (answer === "Open Login Terminal") {
      await openLoginTerminal(root);
      vscode.window.showInformationMessage("After OpenAI login finishes, click Codex Watchdog: Start Guard again.");
    }

    return false;
  }

  async function openLoginTerminal(rootArg) {
    const root = rootArg || await getProjectRoot();
    if (!root) {
      return;
    }
    await ensureCodexHome(root);
    const codexBin = await resolveCodexBin(root);
    const codexHome = codexHomeSetting(root);
    const terminal = vscode.window.createTerminal({
      name: "Codex Watchdog Login",
      cwd: root,
      env: {
        CODEX_BIN: codexBin,
        CODEX_HOME: codexHome,
        CUDA_VISIBLE_DEVICES: ""
      }
    });
    terminal.show();
    const projectCli = path.join(root, "agent", "bin", "watchdog");
    if (fs.existsSync(projectCli)) {
      terminal.sendText("./agent/bin/watchdog login; echo; ./agent/bin/watchdog status");
    } else {
      terminal.sendText(`CODEX_HOME=${shellQuote(codexHome)} ${shellQuote(codexBin)} login; echo; CODEX_HOME=${shellQuote(codexHome)} ${shellQuote(codexBin)} login status`);
    }
  }

  async function getTimerStatus(root) {
    try {
      const units = unitNames(root);
      const active = await run("systemctl", ["--user", "is-active", units.timer], { allowFailure: true, timeout: 5000 });
      const enabled = await run("systemctl", ["--user", "is-enabled", units.timer], { allowFailure: true, timeout: 5000 });
      const next = await run("systemctl", ["--user", "list-timers", units.timer, "--no-pager", "--no-legend"], { allowFailure: true, timeout: 5000 });

      const activeText = (active.stdout || active.stderr || "").trim() || "unknown";
      const enabledText = (enabled.stdout || enabled.stderr || "").trim() || "unknown";
      const nextText = (next.stdout || next.stderr || "").trim();
      const isActive = activeText === "active";
      const isEnabled = enabledText === "enabled";

      return {
        isActive,
        isEnabled,
        activeText,
        enabledText,
        nextText,
        needsReinstall: false,
        warningText: "",
        text: [
          units.timer,
          `active: ${activeText}`,
          `enabled: ${enabledText}`,
          nextText ? `next: ${nextText}` : "next: not scheduled or systemd user timer unavailable"
        ].join("\n")
      };
    } catch (error) {
      return {
        isActive: false,
        isEnabled: false,
        activeText: "unknown",
        enabledText: "unknown",
        nextText: "",
        needsReinstall: false,
        warningText: "",
        text: `Could not read timer status: ${error.message || String(error)}`
      };
    }
  }

  function userSystemdUnitDir() {
    return path.join(os.homedir(), ".config", "systemd", "user");
  }

  function readWatcherUnitDrift(root, settings, unitDir = userSystemdUnitDir()) {
    const units = unitNames(root);
    const servicePath = path.join(unitDir, units.service);
    const timerPath = path.join(unitDir, units.timer);
    if (!fs.existsSync(servicePath) || !fs.existsSync(timerPath)) {
      return {
        installed: false,
        needsReinstall: false,
        reasons: [],
        text: ""
      };
    }
    const serviceText = fs.readFileSync(servicePath, "utf8");
    const timerText = fs.readFileSync(timerPath, "utf8");
    const checks = [
      [`Environment=CODEX_BIN=${systemdEnvValue(settings.codexBin)}`, "Codex binary"],
      [`Environment=CODEX_HOME=${systemdEnvValue(settings.codexHome)}`, "Codex home"],
      [`Environment=CODEX_SANDBOX_MODE=${systemdEnvValue(settings.sandboxMode)}`, "sandbox mode"],
      [`Environment=WATCHDOG_TIMEOUT_MINUTES=${settings.timeoutMinutes}`, "timeout minutes"],
      [`Environment=WATCHDOG_COMPACT_EVERY_RUNS=${settings.compactEveryRuns}`, "compact cadence"],
      [`Environment=WATCHDOG_ROLE=${systemdEnvValue(settings.role)}`, "watchdog role"],
      [`Environment=WATCHDOG_PHASE_OFFSET_MINUTES=${settings.phaseOffsetMinutes}`, "phase offset"],
      [`Environment=WATCHDOG_SUPERVISOR_LIGHT_FOLLOWUP=${settings.supervisorLightFollowup ? "1" : "0"}`, "supervisor light followup"],
      [`Environment=WATCHDOG_SUPERVISOR_AUDIT_EVERY_RUNNER_RUNS=${settings.supervisorAuditEveryRunnerRuns}`, "supervisor audit cadence"]
    ];
    const reasons = [];
    for (const [needle, label] of checks) {
      if (!serviceText.includes(needle)) {
        reasons.push(`${label} differs from the installed service`);
      }
    }
    if (!timerText.includes(`OnActiveSec=${settings.phaseOffsetMinutes}min`)) {
      reasons.push("phase offset differs from the installed timer");
    }
    if (!timerText.includes(`OnUnitActiveSec=${settings.intervalMinutes}min`)) {
      reasons.push("repeat interval differs from the installed timer");
    }
    return {
      installed: true,
      needsReinstall: reasons.length > 0,
      reasons,
      text: reasons.length
        ? `Installed timer units still reference older watchdog settings. Re-run Start Guard or ./agent/bin/watchdog timer-install.\n- ${reasons.join("\n- ")}`
        : ""
    };
  }

  function readJsonFileIfExists(file, fallback = null) {
    if (!fs.existsSync(file)) {
      return fallback;
    }
    try {
      return JSON.parse(fs.readFileSync(file, "utf8"));
    } catch (_error) {
      return fallback;
    }
  }

  function countVisibleEntries(dir) {
    try {
      return fs.readdirSync(dir).filter((name) => name && !name.startsWith(".")).length;
    } catch (_error) {
      return 0;
    }
  }

  function markdownFieldValue(text, label) {
    const match = String(text || "").match(new RegExp(`^\\s*[-*]?\\s*${label}\\s*:\\s*(.+?)\\s*$`, "im"));
    return match ? match[1].trim() : "";
  }

  function isTruthyMarkdownValue(value) {
    const normalized = String(value || "").trim().toLowerCase();
    return ["true", "yes", "1", "on"].includes(normalized);
  }

  function inspectProjectRuntimeClarity(root) {
    const signals = [];
    const pauseFile = path.join(root, "agent", "control", "PAUSE");
    if (fs.existsSync(pauseFile)) {
      const pauseText = readFilePrefix(pauseFile, 2048).trim();
      signals.push({
        level: "warn",
        text: [
          "The guard is paused by agent/control/PAUSE.",
          pauseText || "Open Resume Guard when you want timer wakeups to call Codex again."
        ].join("\n")
      });
    }

    const runState = readJsonFileIfExists(path.join(root, "agent", "RUN_STATE.json"), {});
    if (runState && runState.blocker_type === "stale_state") {
      signals.push({
        level: "warn",
        text: "RUN_STATE.json currently reports blocker_type=stale_state. Treat old failed/preflight records as historical until BLOCKERS.md or the latest report says they are still active."
      });
    }

    const reviewPendingPath = path.join(root, "agent", "REVIEW_PENDING.md");
    if (fs.existsSync(reviewPendingPath)) {
      const reviewText = fs.readFileSync(reviewPendingPath, "utf8");
      const state = markdownFieldValue(reviewText, "state");
      const pendingSend = isTruthyMarkdownValue(markdownFieldValue(reviewText, "pending_send"));
      const requiresHuman = isTruthyMarkdownValue(markdownFieldValue(reviewText, "requires_human_review"));
      if (state === "pending_send" || pendingSend || requiresHuman) {
        signals.push({
          level: "warn",
          text: `Review pending is active (${state || "review_required"}). This is a review/handoff wait inside the project, not a Codex login/runtime bootstrap failure.`
        });
      }
    }

    const queueCounts = {
      queued: countVisibleEntries(path.join(root, "agent", "queue", "queued")) + countVisibleEntries(path.join(root, "gpu_queue")) + countVisibleEntries(path.join(root, "cpu_queue")),
      running: countVisibleEntries(path.join(root, "agent", "queue", "running")) + countVisibleEntries(path.join(root, "gpu_running")) + countVisibleEntries(path.join(root, "cpu_running")),
      done: countVisibleEntries(path.join(root, "agent", "queue", "done")) + countVisibleEntries(path.join(root, "gpu_done")) + countVisibleEntries(path.join(root, "cpu_done")),
      failed: countVisibleEntries(path.join(root, "agent", "queue", "failed")) + countVisibleEntries(path.join(root, "gpu_failed")) + countVisibleEntries(path.join(root, "cpu_failed"))
    };
    const queueText = `Queue snapshot: queued=${queueCounts.queued}, running=${queueCounts.running}, done=${queueCounts.done}, failed=${queueCounts.failed}`;
    if (queueCounts.running > 0 && queueCounts.failed > 0) {
      signals.push({
        level: "warn",
        text: `Running and failed queue records coexist (${queueCounts.running} running, ${queueCounts.failed} failed). Treat failed entries as historical until the newest report or queue runner refresh says they are still live blockers.`
      });
    }

    const reconciliation = readJsonFileIfExists(path.join(root, "agent", "status", "SUPERVISOR_STALE_STATE_RECONCILIATION.json"), {});
    if (reconciliation && reconciliation.timestamp_utc) {
      const changed = reconciliation.reconciliation && reconciliation.reconciliation.changed === true;
      signals.push({
        level: changed ? "ok" : "muted",
        text: `Supervisor stale-state reconciliation last ran at ${reconciliation.timestamp_utc}${changed ? " and reported changed=true." : "."}`
      });
    }

    return { queueText, signals };
  }

  return {
    effectiveWatchdogSettings,
    renderWatchdogEnv,
    writeSystemdUnits,
    ensureCodexHome,
    inspectWatcherHomeBootstrapState,
    inspectWatcherHomeBootstrap,
    seedWatcherHomeBootstrapFromProfilePaths,
    seedWatcherHomeAuthFromMainProfile,
    getCodexLoginStatus,
    confirmLoginIfNeeded,
    openLoginTerminal,
    getTimerStatus,
    readWatcherUnitDrift,
    inspectProjectRuntimeClarity
  };
}

module.exports = {
  createRuntimeHelpers
};
