"use strict";

function createRuntimeSystemdHelpers({
  fs,
  fsp,
  path,
  os,
  output,
  effectiveWatchdogSettings,
  run,
  ensureDir,
  unitNames,
  systemdQuote,
  systemdPathValue,
  systemdEnvValue,
  shellQuote
}) {
  async function renderWatchdogEnv(root) {
    const settings = await effectiveWatchdogSettings(root);
    return [
      "# Generated by Codex Watchdog. No secrets are stored here.",
      "# This file keeps VSCode control-panel startup and project-local CLI startup aligned.",
      `CODEX_BIN=${shellQuote(settings.codexBin)}`,
      `CODEX_HOME=${shellQuote(settings.codexHome)}`,
      `CODEX_SANDBOX_MODE=${shellQuote(settings.sandboxMode)}`,
      `WATCHDOG_INTERVAL_MINUTES=${shellQuote(String(settings.intervalMinutes))}`,
      `WATCHDOG_TIMEOUT_MINUTES=${shellQuote(String(settings.timeoutMinutes))}`,
      `WATCHDOG_COMPACT_EVERY_RUNS=${shellQuote(String(settings.compactEveryRuns))}`,
      `WATCHDOG_ROLE=${shellQuote(settings.role)}`,
      `WATCHDOG_PHASE_OFFSET_MINUTES=${shellQuote(String(settings.phaseOffsetMinutes))}`,
      `WATCHDOG_SUPERVISOR_LIGHT_FOLLOWUP=${shellQuote(settings.supervisorLightFollowup ? "1" : "0")}`,
      `WATCHDOG_SUPERVISOR_AUDIT_EVERY_RUNNER_RUNS=${shellQuote(String(settings.supervisorAuditEveryRunnerRuns))}`,
      `WATCHDOG_SERVICE_PREFIX=${shellQuote(settings.servicePrefix)}`,
      ""
    ].join("\n");
  }

  async function writeSystemdUnits(root, units) {
    const unitDir = userSystemdUnitDir();
    await ensureDir(unitDir);

    const settings = await effectiveWatchdogSettings(root);
    const interval = settings.intervalMinutes;
    const timeout = settings.timeoutMinutes;
    const codexBin = settings.codexBin;
    const codexHome = settings.codexHome;
    const sandboxMode = settings.sandboxMode;
    const compactEveryRuns = settings.compactEveryRuns;
    const role = settings.role;
    const phaseOffsetMinutes = settings.phaseOffsetMinutes;
    const supervisorLightFollowup = settings.supervisorLightFollowup ? "1" : "0";
    const supervisorAuditEveryRunnerRuns = settings.supervisorAuditEveryRunnerRuns;

    const service = [
      "[Unit]",
      `Description=Codex project watcher for ${path.basename(root)}`,
      "",
      "[Service]",
      "Type=oneshot",
      `WorkingDirectory=${systemdPathValue(root)}`,
      `ExecStart=${systemdQuote("/usr/bin/env")} bash ${systemdQuote(path.join(root, "agent", "bin", "run_watchdog.sh"))}`,
      `Environment=CODEX_BIN=${systemdEnvValue(codexBin)}`,
      `Environment=CODEX_HOME=${systemdEnvValue(codexHome)}`,
      `Environment=CODEX_SANDBOX_MODE=${systemdEnvValue(sandboxMode)}`,
      `Environment=WATCHDOG_TIMEOUT_MINUTES=${timeout}`,
      `Environment=WATCHDOG_COMPACT_EVERY_RUNS=${compactEveryRuns}`,
      `Environment=WATCHDOG_ROLE=${systemdEnvValue(role)}`,
      `Environment=WATCHDOG_PHASE_OFFSET_MINUTES=${phaseOffsetMinutes}`,
      `Environment=WATCHDOG_SUPERVISOR_LIGHT_FOLLOWUP=${supervisorLightFollowup}`,
      `Environment=WATCHDOG_SUPERVISOR_AUDIT_EVERY_RUNNER_RUNS=${supervisorAuditEveryRunnerRuns}`,
      "Environment=CUDA_VISIBLE_DEVICES=",
      "NoNewPrivileges=yes",
      "PrivateTmp=yes",
      "ProtectSystem=full",
      `TimeoutStartSec=${timeout}min`,
      ""
    ].join("\n");

    const timer = [
      "[Unit]",
      `Description=Run Codex project watcher every ${interval} minutes for ${path.basename(root)}`,
      "",
      "[Timer]",
      `OnActiveSec=${phaseOffsetMinutes}min`,
      `OnUnitActiveSec=${interval}min`,
      "AccuracySec=1min",
      `Unit=${units.service}`,
      "",
      "[Install]",
      "WantedBy=timers.target",
      ""
    ].join("\n");

    await fsp.writeFile(path.join(unitDir, units.service), service);
    await fsp.writeFile(path.join(unitDir, units.timer), timer);
    output.appendLine(`Wrote ${path.join(unitDir, units.service)}`);
    output.appendLine(`Wrote ${path.join(unitDir, units.timer)}`);
  }

  async function getTimerStatus(root) {
    try {
      const units = unitNames(root);
      const active = await run("systemctl", ["--user", "is-active", units.timer], { allowFailure: true, timeout: 5000 });
      const enabled = await run("systemctl", ["--user", "is-enabled", units.timer], { allowFailure: true, timeout: 5000 });
      const next = await run("systemctl", ["--user", "list-timers", units.timer, "--no-pager", "--no-legend"], { allowFailure: true, timeout: 5000 });

      const activeText = (active.stdout || active.stderr || "").trim() || "unknown";
      const enabledText = (enabled.stdout || enabled.stderr || "").trim() || "unknown";
      const nextText = (next.stdout || next.stderr || "").trim();
      const isActive = activeText === "active";
      const isEnabled = enabledText === "enabled";

      return {
        isActive,
        isEnabled,
        activeText,
        enabledText,
        nextText,
        needsReinstall: false,
        warningText: "",
        text: [
          units.timer,
          `active: ${activeText}`,
          `enabled: ${enabledText}`,
          nextText ? `next: ${nextText}` : "next: not scheduled or systemd user timer unavailable"
        ].join("\n")
      };
    } catch (error) {
      return {
        isActive: false,
        isEnabled: false,
        activeText: "unknown",
        enabledText: "unknown",
        nextText: "",
        needsReinstall: false,
        warningText: "",
        text: `Could not read timer status: ${error.message || String(error)}`
      };
    }
  }

  function userSystemdUnitDir() {
    return path.join(os.homedir(), ".config", "systemd", "user");
  }

  function readWatcherUnitDrift(root, settings, unitDir = userSystemdUnitDir()) {
    const units = unitNames(root);
    const servicePath = path.join(unitDir, units.service);
    const timerPath = path.join(unitDir, units.timer);
    if (!fs.existsSync(servicePath) || !fs.existsSync(timerPath)) {
      return {
        installed: false,
        needsReinstall: false,
        reasons: [],
        text: ""
      };
    }
    const serviceText = fs.readFileSync(servicePath, "utf8");
    const timerText = fs.readFileSync(timerPath, "utf8");
    const checks = [
      [`Environment=CODEX_BIN=${systemdEnvValue(settings.codexBin)}`, "Codex binary"],
      [`Environment=CODEX_HOME=${systemdEnvValue(settings.codexHome)}`, "Codex home"],
      [`Environment=CODEX_SANDBOX_MODE=${systemdEnvValue(settings.sandboxMode)}`, "sandbox mode"],
      [`Environment=WATCHDOG_TIMEOUT_MINUTES=${settings.timeoutMinutes}`, "timeout minutes"],
      [`Environment=WATCHDOG_COMPACT_EVERY_RUNS=${settings.compactEveryRuns}`, "compact cadence"],
      [`Environment=WATCHDOG_ROLE=${systemdEnvValue(settings.role)}`, "watchdog role"],
      [`Environment=WATCHDOG_PHASE_OFFSET_MINUTES=${settings.phaseOffsetMinutes}`, "phase offset"],
      [`Environment=WATCHDOG_SUPERVISOR_LIGHT_FOLLOWUP=${settings.supervisorLightFollowup ? "1" : "0"}`, "supervisor light followup"],
      [`Environment=WATCHDOG_SUPERVISOR_AUDIT_EVERY_RUNNER_RUNS=${settings.supervisorAuditEveryRunnerRuns}`, "supervisor audit cadence"]
    ];
    const reasons = [];
    for (const [needle, label] of checks) {
      if (!serviceText.includes(needle)) {
        reasons.push(`${label} differs from the installed service`);
      }
    }
    if (!timerText.includes(`OnActiveSec=${settings.phaseOffsetMinutes}min`)) {
      reasons.push("phase offset differs from the installed timer");
    }
    if (!timerText.includes(`OnUnitActiveSec=${settings.intervalMinutes}min`)) {
      reasons.push("repeat interval differs from the installed timer");
    }
    return {
      installed: true,
      needsReinstall: reasons.length > 0,
      reasons,
      text: reasons.length
        ? `Installed timer units still reference older watchdog settings. Re-run Start Guard or ./agent/bin/watchdog timer-install.\n- ${reasons.join("\n- ")}`
        : ""
    };
  }

  return {
    renderWatchdogEnv,
    writeSystemdUnits,
    getTimerStatus,
    readWatcherUnitDrift
  };
}

module.exports = {
  createRuntimeSystemdHelpers
};
